# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wybierz w jakiej branzy pracujesz.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'branze',
            },
        ),
        migrations.CreateModel(
            name='EngJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Polska nazwa Twojego stanowiska', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Polska nazwa Twojego stanowiska', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_job', models.CharField(max_length=100)),
                ('eng_job', models.CharField(max_length=100)),
                ('opis', models.TextField(help_text='Na czym polega Twoja praca?', max_length=500, verbose_name='opis stanowiska')),
                ('dzien', models.TextField(help_text='Co robiles przez 8 godzin w pracy?', max_length=500, verbose_name='opis dnia')),
                ('branza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addjob.Branza')),
            ],
            options={
                'verbose_name_plural': 'stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Z czym kojarzy Ci sie Twoja praca', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='stanowisko',
            name='tags',
            field=models.ManyToManyField(to='addjob.Tags'),
        ),
    ]
