# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='eng_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addjob.EngJob'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='pl_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addjob.PlJob'),
        ),
    ]
