# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0002_auto_20160212_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanowisko',
            name='sektor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sektors_requests_created', to='addjob.Branza'),
            preserve_default=False,
        ),
    ]
