# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0003_stanowisko_sektor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='branza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branza_requests_created', to='addjob.Branza'),
        ),
    ]
