# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0004_auto_20160212_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanowisko',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engjob',
            name='name',
            field=models.CharField(help_text='Polska nazwa Twojego stanowiska', max_length=100, unique=True, verbose_name='Angielska nazwa'),
        ),
        migrations.AlterField(
            model_name='pljob',
            name='name',
            field=models.CharField(help_text='Polska nazwa Twojego stanowiska', max_length=100, unique=True, verbose_name='Polska nazwa'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='sektor',
            field=models.ForeignKey(help_text='W jakiej baran\u017cy pracujesz?', on_delete=django.db.models.deletion.CASCADE, related_name='sektors_requests_created', to='addjob.Branza'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='tags',
            field=models.ManyToManyField(related_name='tags_request_created', to='addjob.Tags'),
        ),
    ]
