# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0005_auto_20160219_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='sektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sektors_requests_created', to='addjob.Branza'),
        ),
    ]
