# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0006_auto_20160219_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='branza',
            name='slug',
            field=models.SlugField(default='abc'),
            preserve_default=False,
        ),
    ]
