# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0007_branza_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='branza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branza_requests_created', related_query_name='br', to='addjob.Branza'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='sektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sektors_requests_created', related_query_name='br', to='addjob.Branza'),
        ),
    ]
