# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0008_auto_20160220_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='eng_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addjob.EngJob', verbose_name='Angielska nazwa'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='pl_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addjob.PlJob', verbose_name='Polska nazwa'),
        ),
    ]
