# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addjob', '0009_auto_20160220_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='dzien',
            field=models.TextField(help_text='Co robiles przez 8 godzin w pracy?', max_length=1000, verbose_name='opis dnia'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.TextField(help_text='Na czym polega Twoja praca?', max_length=1000, verbose_name='opis stanowiska'),
        ),
    ]
